### PR TITLE
Tapir Safe Mode

### PR DESCRIPTION
**Pull request by willtebbutt**
Follow up from recent ADTypes PR -- this PR ensures that if someone asks for safe mode in when constructing `AutoTapir`, they get safe mode.

### CODE REVIEW

**Comment by willtebbutt** [comment]
Test failures because version 1.2 of ADTypes is not yet available.

**Comment by gdalle** [comment]
The formatting check failed. Also you are polluting my test suite with `@info` messages, is there any way to get rid of them? Perhaps test the unsafe mode here, and both modes on your end?

**Comment by willtebbutt** [comment]
> The formatting check failed. 

Hmm yes, that does appear to be what's happening. Have you considered deploying ReviewDog e.g. as done in [AbstractGPs](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/master/.github/workflows/format.yml) in order to make any formatting issues + fixes appear in the PR?

> Also you are polluting my test suite with @info messages, is there any way to get rid of them?

Hahaha, yes, I am doing that at present.

> Perhaps test the unsafe mode here, and both modes on your end?

Yeah, that's probably the right thing to do. Will fix these problems now.

**Comment by gdalle** [comment]
> Have you considered deploying ReviewDog e.g. as done in [AbstractGPs](https://github.com/JuliaGaussianProcesses/AbstractGPs.jl/blob/master/.github/workflows/format.yml) in order to make any formatting issues + fixes appear in the PR?

From what I've seen, these tools can be extremely noisy and make tons of comments on a single commit, so I like having that check as part of my test suite. Especially when I work on rather ambitious PRs, which is often the case in DI

**Comment by willtebbutt** [comment]
> From what I've seen, these tools can be extremely noisy and make tons of comments on a single commit, so I like having that check as part of my test suite. Especially when I work on rather ambitious PRs, which is often the case in DI

That's completely reasonable.

**Comment by willtebbutt** [comment]
Another bug on my end because testing whether something prints is hard. Will fix and then re-run the tests.

**Review by gdalle — APPROVED** [review]

**Comment by gdalle** [comment]
The printing is not a problem for me, it's just a mild annoyance. Since the tests pass, can I merge and release this?

**Comment by willtebbutt** [comment]
Yes, please do. The next patch version of Tapir will fix the printing issue anyway.

**Pull request merged**
