### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by adrhill**
Adds a logo for DifferentiationInterface:

DI Logo

## Background

The initial concept of *"AD backends holding hands in unity as a group of ∂ seen from above"* was deemed "vomit inducing" by @gdalle's closest circle:
 
Old DI Logo

## Why its great

* It's great!
* Symmetry!
* Julia colors!
* Partials $\partial$ representing the holy trinity of the forward, the reverse and the symbolic!
* Partials $\partial$ representing the colorful diversity of backends in the Julia ecosystem!
* Printable as a sticker!
* Recognizable from a distance, on a favicon or [shields.io badge](https://img.shields.io/badge/Differentiation-Interface-blue&labelColor=white?&labelColor=white&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgdmlld0JveD0iMCAwIDIwMCAyMDAiPgo8ZGVmcz4KPHJhZGlhbEdyYWRpZW50IGlkPSJyYWRpYWwtcGF0dGVybi0wIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgY3g9IjAiIGN5PSI0IiBmeD0iOS43NDAxODMiIGZ5PSIxNi42OTM2NTMiIHI9IjUwIiBncmFkaWVudFRyYW5zZm9ybT0ibWF0cml4KDMuNCwgMCwgMCwgMy40LCAxMDAsIDEwMCkiPgo8c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9InJnYig1OC40JSwgMzQuNSUsIDY5LjglKSIgc3RvcC1vcGFjaXR5PSIxIi8+CjxzdG9wIG9mZnNldD0iMSIgc3RvcC1jb2xvcj0icmdiKDAlLCAwJSwgMCUpIiBzdG9wLW9wYWNpdHk9IjEiLz4KPC9yYWRpYWxHcmFkaWVudD4KPHJhZGlhbEdyYWRpZW50IGlkPSJyYWRpYWwtcGF0dGVybi0xIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgY3g9IjAiIGN5PSI0IiBmeD0iLTE1Ljg2MzExOCIgZnk9IjYuMDg4NDE5IiByPSI1MCIgZ3JhZGllbnRUcmFuc2Zvcm09Im1hdHJpeCgzLjQsIDAsIDAsIDMuNCwgMTAwLCAxMDApIj4KPHN0b3Agb2Zmc2V0PSIwIiBzdG9wLWNvbG9yPSJyZ2IoNzkuNiUsIDIzLjUlLCAyMCUpIiBzdG9wLW9wYWNpdHk9IjEiLz4KPHN0b3Agb2Zmc2V0PSIxIiBzdG9wLWNvbG9yPSJyZ2IoMCUsIDAlLCAwJSkiIHN0b3Atb3BhY2l0eT0iMSIvPgo8L3JhZGlhbEdyYWRpZW50Pgo8cmFkaWFsR3JhZGllbnQgaWQ9InJhZGlhbC1wYXR0ZXJuLTIiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIiBjeD0iMCIgY3k9IjQiIGZ4PSI2LjEyMjkzNSIgZnk9Ii0xMC43ODIwNzMiIHI9IjUwIiBncmFkaWVudFRyYW5zZm9ybT0ibWF0cml4KDMuNCwgMCwgMCwgMy40LCAxMDAsIDEwMCkiPgo8c3RvcCBvZmZzZXQ9IjAiIHN0b3AtY29sb3I9InJnYigyMiUsIDU5LjYlLCAxNC45JSkiIHN0b3Atb3BhY2l0eT0iMSIvPgo8c3RvcCBvZmZzZXQ9IjEiIHN0b3AtY29sb3I9InJnYigwJSwgMCUsIDAlKSIgc3RvcC1vcGFjaXR5PSIxIi8+CjwvcmFkaWFsR3JhZGllbnQ+CjwvZGVmcz4KPHBhdGggZmlsbC1ydWxlPSJub256ZXJvIiBmaWxsPSJ1cmwoI3JhZGlhbC1wYXR0ZXJuLTApIiBkPSJNIDExMC4yMzQzNzUgMTgwLjYyMTA5NCBMIDEwOS4zMjAzMTIgMTkzLjkyOTY4OCBDIDEwMS4wMjM0MzggMTk1LjAxOTUzMSA5My44NzEwOTQgMTk0LjA1ODU5NCA4Ny44NjcxODggMTkxLjA0Njg3NSBDIDgxLjg1OTM3NSAxODguMDM5MDYyIDc3LjMwNDY4OCAxODMuNTY2NDA2IDc0LjIwMzEyNSAxNzcuNjMyODEyIEMgNzAuNDg0Mzc1IDE3MC41MjM0MzggNjkuOTM3NSAxNjMuNSA3Mi41NTg1OTQgMTU2LjU3NDIxOSBDIDc2LjMxMjUgMTQ2LjQyOTY4OCA4NS42MTcxODggMTM3LjQ3NjU2MiAxMDAuNDc2NTYyIDEyOS43MDcwMzEgQyAxMTMuMjc3MzQ0IDEyMy4wMTU2MjUgMTI2Ljc0NjA5NCAxMTguNTY2NDA2IDE0MC44OTA2MjUgMTE2LjM1NTQ2OSBDIDE1NS4wMzUxNTYgMTE0LjE0NDUzMSAxNjYuNjQ4NDM4IDExNS4yNSAxNzUuNzM4MjgxIDExOS42Nzk2ODggQyAxODQuODI4MTI1IDEyNC4xMDU0NjkgMTkxLjQ1MzEyNSAxMzAuMjkyOTY5IDE5NS42MDU0NjkgMTM4LjIzODI4MSBDIDE5OS4xNDQ1MzEgMTQ1LjAwMzkwNiAxOTkuNzY1NjI1IDE1MS42ODc1IDE5Ny40Njg3NSAxNTguMjg5MDYyIEMgMTk1LjE3NTc4MSAxNjQuODkwNjI1IDE4OS44NTkzNzUgMTcwLjM3MTA5NCAxODEuNTIzNDM4IDE3NC43MjY1NjIgQyAxNzMuNzczNDM4IDE3OC43NzczNDQgMTY1LjIzMDQ2OSAxODAuNTMxMjUgMTU1Ljg5MDYyNSAxNzkuOTgwNDY5IEMgMTQ2LjU0Njg3NSAxNzkuNDMzNTk0IDEzNy40OTYwOTQgMTc1Ljg1OTM3NSAxMjguNzM4MjgxIDE2OS4yNTc4MTIgQyAxMTkuOTgwNDY5IDE2Mi42NjAxNTYgMTEyLjUxOTUzMSAxNTMuMTY0MDYyIDEwNi4zNTU0NjkgMTQwLjc3NzM0NCBDIDk2LjU3NDIxOSAxNDUuOTUzMTI1IDkwLjI2NTYyNSAxNTEuNTYyNSA4Ny40Mjk2ODggMTU3LjYwNTQ2OSBDIDg1LjMzMjAzMSAxNjIuMDc0MjE5IDg1LjQ0OTIxOSAxNjYuNTM5MDYyIDg3Ljc4MTI1IDE3MSBDIDg5LjU1MDc4MSAxNzQuMzgyODEyIDkyLjA2MjUgMTc2LjgzMjAzMSA5NS4zMjAzMTIgMTc4LjM0NzY1NiBDIDk4LjU3ODEyNSAxNzkuODU5Mzc1IDEwMy41NTA3ODEgMTgwLjYxNzE4OCAxMTAuMjM0Mzc1IDE4MC42MjEwOTQgWiBNIDEyMC4zNTU0NjkgMTM0LjU4MjAzMSBDIDEyMS4wNTA3ODEgMTM2LjAzMTI1IDEyMS41ODk4NDQgMTM3LjEyNSAxMjEuOTcyNjU2IDEzNy44NTkzNzUgQyAxMjUuNDg0Mzc1IDE0NC41NzgxMjUgMTMwLjEyMTA5NCAxNTAuMTMyODEyIDEzNS44ODI4MTIgMTU0LjUxOTUzMSBDIDE0MS42NDA2MjUgMTU4LjkwNjI1IDE0Ny44MzU5MzggMTYxLjI4OTA2MiAxNTQuNDYwOTM4IDE2MS42NjQwNjIgQyAxNjEuMDg5ODQ0IDE2Mi4wMzkwNjIgMTY2Ljk1MzEyNSAxNjAuODk0NTMxIDE3Mi4wNTQ2ODggMTU4LjIzMDQ2OSBDIDE3NS44Nzg5MDYgMTU2LjIzMDQ2OSAxNzguNDE3OTY5IDE1My41ODk4NDQgMTc5LjY3MTg3NSAxNTAuMzEyNSBDIDE4MC45MjU3ODEgMTQ3LjAzNTE1NiAxODAuODIwMzEyIDE0NCAxNzkuMzU5Mzc1IDE0MS4yMDMxMjUgQyAxNzYuMzA4NTk0IDEzNS4zNjcxODggMTcwLjcwNzAzMSAxMzEuNTE5NTMxIDE2Mi41NTQ2ODggMTI5LjY2NDA2MiBDIDE1MC44NDc2NTYgMTI2Ljk4MDQ2OSAxMzYuNzgxMjUgMTI4LjYxNzE4OCAxMjAuMzU1NDY5IDEzNC41ODIwMzEgWiBNIDEyMC4zNTU0NjkgMTM0LjU4MjAzMSAiLz4KPHBhdGggZmlsbC1ydWxlPSJub256ZXJvIiBmaWxsPSJ1cmwoI3JhZGlhbC1wYXR0ZXJuLTEpIiBkPSJNIDM2Ljg0Mzc1IDg4Ljk0OTIxOSBMIDI1Ljc3MzQzOCA4MS41MDc4MTIgQyAyOC45NzY1NjIgNzMuNzc3MzQ0IDMzLjM4NjcxOSA2OC4wNjI1IDM4Ljk5NjA5NCA2NC4zNjcxODggQyA0NC42MDU0NjkgNjAuNjY3OTY5IDUwLjc1NzgxMiA1OC45NjA5MzggNTcuNDQ1MzEyIDU5LjI0MjE4OCBDIDY1LjQ2NDg0NCA1OS41NzgxMjUgNzEuODE2NDA2IDYyLjYxMzI4MSA3Ni41MDc4MTIgNjguMzQ3NjU2IEMgODMuNDE0MDYyIDc2LjY2Nzk2OSA4Ni41MTU2MjUgODkuMjAzMTI1IDg1LjgxMjUgMTA1Ljk1NzAzMSBDIDg1LjIwNzAzMSAxMjAuMzg2NzE5IDgyLjMyODEyNSAxMzQuMjgxMjUgNzcuMTcxODc1IDE0Ny42MzI4MTIgQyA3Mi4wMTU2MjUgMTYwLjk4ODI4MSA2NS4yNDYwOTQgMTcwLjQ5NjA5NCA1Ni44NjcxODggMTc2LjE1MjM0NCBDIDQ4LjQ4ODI4MSAxODEuODEyNSAzOS44MjAzMTIgMTg0LjQ1MzEyNSAzMC44NjMyODEgMTg0LjA3ODEyNSBDIDIzLjIzNDM3NSAxODMuNzU3ODEyIDE3LjEzMjgxMiAxODAuOTUzMTI1IDEyLjU2MjUgMTc1LjY2Nzk2OSBDIDcuOTkyMTg4IDE3MC4zNzg5MDYgNS45MDYyNSAxNjMuMDM1MTU2IDYuMzAwNzgxIDE1My42MzY3MTkgQyA2LjY2Nzk2OSAxNDQuOTAyMzQ0IDkuNDIxODc1IDEzNi42MjUgMTQuNTcwMzEyIDEyOC44MDg1OTQgQyAxOS43MTQ4NDQgMTIwLjk5MjE4OCAyNy4zMzU5MzggMTE0Ljk0NTMxMiAzNy40Mjk2ODggMTEwLjY2MDE1NiBDIDQ3LjUyMzQzOCAxMDYuMzc1IDU5LjQ3NjU2MiAxMDQuNjYwMTU2IDczLjI4NTE1NiAxMDUuNTE1NjI1IEMgNzMuNjk1MzEyIDk0LjQ1NzAzMSA3MS45OTIxODggODYuMTg3NSA2OC4xNzk2ODggODAuNzEwOTM4IEMgNjUuMzU5Mzc1IDc2LjY2MDE1NiA2MS40Mjk2ODggNzQuNTI3MzQ0IDU2LjM5ODQzOCA3NC4zMTY0MDYgQyA1Mi41ODU5MzggNzQuMTU2MjUgNDkuMjA3MDMxIDc1LjEwOTM3NSA0Ni4yNjk1MzEgNzcuMTc1NzgxIEMgNDMuMzI4MTI1IDc5LjIzODI4MSA0MC4xODc1IDgzLjE2NDA2MiAzNi44NDM3NSA4OC45NDkyMTkgWiBNIDcxLjY1MjM0NCAxMjAuNzM0Mzc1IEMgNzAuMDUwNzgxIDEyMC42MTMyODEgNjguODM1OTM4IDEyMC41MzEyNSA2OC4wMDc4MTIgMTIwLjUgQyA2MC40MzM1OTQgMTIwLjE3OTY4OCA1My4zMDQ2ODggMTIxLjQxNzk2OSA0Ni42MjUgMTI0LjIxNDg0NCBDIDM5Ljk0MTQwNiAxMjcuMDA3ODEyIDM0Ljc4MTI1IDEzMS4xNzk2ODggMzEuMTQ0NTMxIDEzNi43MzQzNzUgQyAyNy41MDM5MDYgMTQyLjI4NTE1NiAyNS41NjY0MDYgMTQ3LjkzNzUgMjUuMzI0MjE5IDE1My42ODc1IEMgMjUuMTQ0NTMxIDE1OCAyNi4xNjAxNTYgMTYxLjUxNTYyNSAyOC4zNzEwOTQgMTY0LjI0MjE4OCBDIDMwLjU4MjAzMSAxNjYuOTY0ODQ0IDMzLjI2NTYyNSAxNjguMzkwNjI1IDM2LjQxNzk2OSAxNjguNTIzNDM4IEMgNDIuOTk2MDk0IDE2OC44MDA3ODEgNDkuMTI4OTA2IDE2NS44NzEwOTQgNTQuODEyNSAxNTkuNzQyMTg4IEMgNjIuOTkyMTg4IDE1MC45NDUzMTIgNjguNjA1NDY5IDEzNy45NDE0MDYgNzEuNjUyMzQ0IDEyMC43MzQzNzUgWiBNIDcxLjY1MjM0NCAxMjAuNzM0Mzc1ICIvPgo8cGF0aCBmaWxsLXJ1bGU9Im5vbnplcm8iIGZpbGw9InVybCgjcmFkaWFsLXBhdHRlcm4tMikiIGQ9Ik0gMTUyLjkyMTg3NSA3MS4yMzA0NjkgTCAxNjQuOTAyMzQ0IDY1LjM2MzI4MSBDIDE2OS45OTYwOTQgNzIuMDAzOTA2IDE3Mi43NDIxODggNzguNjc5Njg4IDE3My4xMzY3MTkgODUuMzg2NzE5IEMgMTczLjUzNTE1NiA5Mi4wOTM3NSAxNzEuOTQxNDA2IDk4LjI3MzQzOCAxNjguMzUxNTYyIDEwMy45MjU3ODEgQyAxNjQuMDUwNzgxIDExMC43MDMxMjUgMTU4LjI0NjA5NCAxMTQuNjg3NSAxNTAuOTMzNTk0IDExNS44Nzg5MDYgQyAxNDAuMjc3MzQ0IDExNy42OTkyMTkgMTI3Ljg2NzE4OCAxMTQuMTIxMDk0IDExMy43MTA5MzggMTA1LjEzNjcxOSBDIDEwMS41MTU2MjUgOTcuMzk4NDM4IDkwLjkyNTc4MSA4Ny45NTMxMjUgODEuOTM3NSA3Ni44MTI1IEMgNzIuOTUzMTI1IDY1LjY2Nzk2OSA2OC4xMDU0NjkgNTUuMDU0Njg4IDY3LjM5NDUzMSA0NC45Njg3NSBDIDY2LjY4MzU5NCAzNC44ODI4MTIgNjguNzMwNDY5IDI2LjA1NDY4OCA3My41MzEyNSAxOC40ODgyODEgQyA3Ny42MjUgMTIuMDM5MDYyIDgzLjEwMTU2MiA4LjE2MDE1NiA4OS45NjQ4NDQgNi44NDM3NSBDIDk2LjgyODEyNSA1LjUzMTI1IDEwNC4yMzA0NjkgNy4zOTQ1MzEgMTEyLjE3NTc4MSAxMi40Mzc1IEMgMTE5LjU1ODU5NCAxNy4xMjEwOTQgMTI1LjM0NzY1NiAyMy42NDQ1MzEgMTI5LjU0Mjk2OSAzMi4wMTE3MTkgQyAxMzMuNzM4MjgxIDQwLjM3NSAxMzUuMTY3OTY5IDUwIDEzMy44MzIwMzEgNjAuODgyODEyIEMgMTMyLjQ5NjA5NCA3MS43NjU2MjUgMTI4LjAwMzkwNiA4Mi45NzY1NjIgMTIwLjM1NTQ2OSA5NC41MDc4MTIgQyAxMjkuNzMwNDY5IDEwMC4zOTA2MjUgMTM3Ljc0MjE4OCAxMDMuMDUwNzgxIDE0NC4zOTQ1MzEgMTAyLjQ4ODI4MSBDIDE0OS4zMTI1IDEwMi4wNzAzMTIgMTUzLjEyMTA5NCA5OS43MzQzNzUgMTU1LjgyMDMxMiA5NS40ODA0NjkgQyAxNTcuODYzMjgxIDkyLjI1NzgxMiAxNTguNzI2NTYyIDg4Ljg1OTM3NSAxNTguNDEwMTU2IDg1LjI4MTI1IEMgMTU4LjA4OTg0NCA4MS43MDMxMjUgMTU2LjI2MTcxOSA3Ny4wMTk1MzEgMTUyLjkyMTg3NSA3MS4yMzA0NjkgWiBNIDEwNy45OTYwOTQgODUuNDg0Mzc1IEMgMTA4LjkwMjM0NCA4NC4xNTYyNSAxMDkuNTc4MTI1IDgzLjE0NDUzMSAxMTAuMDE5NTMxIDgyLjQ0NTMxMiBDIDExNC4wODIwMzEgNzYuMDQyOTY5IDExNi41NzQyMTkgNjkuMjUgMTE3LjQ5NjA5NCA2Mi4wNjY0MDYgQyAxMTguNDE3OTY5IDU0Ljg4NjcxOSAxMTcuMzgyODEyIDQ4LjMzMjAzMSAxMTQuMzk0NTMxIDQyLjQwMjM0NCBDIDExMS40MDYyNSAzNi40NzY1NjIgMTA3LjQ4MDQ2OSAzMS45Njg3NSAxMDIuNjIxMDk0IDI4Ljg4NjcxOSBDIDk4Ljk3NjU2MiAyNi41NzQyMTkgOTUuNDIxODc1IDI1LjY5NTMxMiA5MS45NTcwMzEgMjYuMjQ2MDk0IEMgODguNDkyMTg4IDI2LjgwMDc4MSA4NS45MTQwNjIgMjguNDEwMTU2IDg0LjIyMjY1NiAzMS4wNzQyMTkgQyA4MC42OTUzMTIgMzYuNjMyODEyIDgwLjE2NDA2MiA0My40MDYyNSA4Mi42MzI4MTIgNTEuMzk4NDM4IEMgODYuMTYwMTU2IDYyLjg3ODkwNiA5NC42MTMyODEgNzQuMjM4MjgxIDEwNy45OTYwOTQgODUuNDg0Mzc1IFogTSAxMDcuOTk2MDk0IDg1LjQ4NDM3NSAiLz4KPC9zdmc+Cg==)!

### CODE REVIEW

**Comment by gdalle** [comment]
I love this (and my closest circle stands by their initial opinion)

**Review by gdalle — APPROVED** [review]
What does the favicon in the assets do? I thought only `logo.svg` is needed

**Comment by adrhill** [comment]
As far as I know, the favicon is necessary to get the logo to appear in browser tabs.
https://documenter.juliadocs.org/stable/lib/internals/writers/#Documenter.HTMLWriter.HTML
(Ctrl+F `.ico`)

**Comment by adrhill** [comment]
The Pluto notebook documents an ImageMagick one-liner to create the favicon from the SVG:
```bash
convert -background transparent logo.svg -define icon:auto-resize=256,128,48,32,16 favicon.ico
```

**Pull request merged**
